### PR TITLE
Update discord url

### PR DESCRIPTION
**Pull request by LA3QMA**
Added the correct Discord URL

### CODE REVIEW

**Comment by Mashintime** [comment]
Thanks, don't know why the invite links keep expiring.  😦

**Comment by DJ2LS** [comment]
@LA3QMA is this the link I've sent you?

**Comment by LA3QMA** [comment]
No it was a link i created. But it should be the one you sent as this probably have a longer expire time.

**Comment by DJ2LS** [comment]
I created https://discord.freedata.app/
Which forwards to the invitation URL. Sharing should be easier then and also in app usage.

**Comment by DJ2LS** [comment]
@LA3QMA csn you change the link so we can merge this PR?

**Comment by DJ2LS** [comment]
@LA3QMA i created a redirection for "discord.freedata.app" . This would allow us, changing invitation links without app changes

**Comment by LA3QMA** [comment]
ahh QSL then i'll close this one.

**Comment by DJ2LS** [comment]
@LA3QMA yes but the url still needs to be changed in app 🙂

**Pull request closed without merging**
