### PR TITLE
Internal rigctld tweaks for windows users

### PR DESCRIPTION
**Pull request by Mashintime**
- Process custom arguments for rigctld for all platforms
- Search c:\program files*\Hamlib*\bin for rigctld binaries on Windows
- Remove default custom args from example config

### CODE REVIEW

**Comment by DJ2LS** [comment]
Great, thanks @Mashintime  
What about removing the 32bit version of Hamlib from build process ( nsis )?

@dk5sm might this fix your path problem you've reported?

**Comment by Mashintime** [comment]
NSIS?  We should only support 64 bit in my opinion for binary packages.  

But if a user wants to use a 32 bit version of hamlib, I see no issues with supporting that and checking if it's available.

**Review by DJ2LS — APPROVED** [review]

**Comment by DJ2LS** [comment]
@Mashintime I've removed the 32bit build separately. We can merge if you want

**Comment by Mashintime** [comment]
I'm good with merging.

**Pull request merged**
