### PR TITLE
small arq improvements

### PR DESCRIPTION
**Pull request by DJ2LS**
- [x] Reject ARQ_RAW command if in ARQ State

### CODE REVIEW

**Comment by DJ2LS** [comment]
@Mashintime version information is gone in app title. That's an important information for debugging.

**Comment by Mashintime** [comment]
Agreed.  I'll add it in ls-gui

**Comment by Mashintime** [comment]
Version in title is in ls-gui now.

**Comment by DJ2LS** [comment]
adresses also #340

**Comment by DJ2LS** [comment]
when merging this PR we ,just publish a new release because of breaking coding when sending beacon, ping or cq @Mashintime

**Pull request merged**
