### PR TITLE
chat related changes

### PR DESCRIPTION
**Pull request by DJ2LS**
And another attempt ....

Broken:
- [x] If user not exists in database, use placeholder
- [x] get file list
- [x] get user profile

### CODE REVIEW

**Comment by DJ2LS** [comment]
@Mashintime trying to fix chat related things here....

**Comment by DJ2LS** [comment]
okay, I managed to get shared folder working now....

**Comment by DJ2LS** [comment]
And user profile is now more stable as well....

@Mashintime , could you have a look at the changes? These response request things are still not that easy to implement. I splatted user data and shared folder now. 

This PR could be used as 0.8.0-alpha.2 if you're fine with changes

**Review by Mashintime — APPROVED** [review]
Looks good to me.

**Pull request merged**
