### PR TITLE
Add an explorer button to the gui

### PR DESCRIPTION
**Pull request by Mashintime**
Trying to become more familiar with electron and git.  Thought this would be an easy feature to add.  Adds an explorer button before the chat button.

### CODE REVIEW

**Comment by DJ2LS** [comment]
Nice, @Mashintime 🎉 I'll try testing this, later!

**Review by DJ2LS — APPROVED** [review]
Should work from a theoretical point of view

**Comment by DJ2LS** [comment]
@Mashintime regarding to used branches: I suggest committing to "main" next time and naming the own branch with "<developer tag>-<name>"

But that's okay for now for this one.

**Comment by Mashintime** [comment]
Will do, thanks for the feedback.

**Comment by DJ2LS** [comment]
@Mashintime if you're interested, you can also have a look for integration of Vue framework. This is the next big step and reducing CPU load as well.

**Comment by DJ2LS** [comment]
@Mashintime Button is working here for me. Could you change the color to "primary", so we have more consistent colors used. We should try to not use too much different colors, I think. 
Also nice idea, implementing the callsign into url, so we can do some more improvements to the Explorer somewhen.

**Comment by DJ2LS** [comment]
@dk5sm , any further suggestions?

**Comment by Mashintime** [comment]
Sure, do I just add another commit to my fork to change it?  Figured maybe some day you could use it to highlight heard/heard by stations, center on the station if location data is unavailable, or what not.

**Comment by DJ2LS** [comment]
@Mashintime yes, just commit to your  branch and it will be available here.

**Comment by Mashintime** [comment]
Done, I believe.

**Review by DJ2LS — APPROVED** [review]
Great, @Mashintime I'm going to merge this, okay?

**Comment by Mashintime** [comment]
Sounds good, thanks for the help and the work you're doing.

**Pull request merged**
