### PR TITLE
Waterfall theme selector and some optimizations

### PR DESCRIPTION
**Pull request by Mashintime**
Rebased on main.

Click event changed to 'change' for waterfall theme selector.

Was fun!

### CODE REVIEW

**Comment by DJ2LS** [comment]
> Rebased on main.
> 
> Click event changed to 'change' for waterfall theme selector.
> 
> Was fun!

Great, @Mashintime 🥳 Also have a look at checks. In this case theres a CodeFactor check which is failing. If possible, please try fixing this.

Do you plan to do some other changes?

**Comment by DJ2LS** [comment]
@Mashintime here's a another needed feature request, I just got by instant message:

```
When pressing "CQ" or "PING", button should be disabled and bootstrap spinner should be inside the corresponding button. 
https://getbootstrap.com/docs/5.2/components/spinners/
```


I suggest, creating a new function, we need to pass the html object to and a specific timeout, until it's getting released. 

Challenge accepted? 😃

**Comment by Mashintime** [comment]
I added a return in the spectrum/waterfall code for code that would never be needed in it's current use case.  If you never plan on showing the spectrum that would render above the waterfall if enabled I'd be happy to remove it.  But wanted to double check.

I'll work on things off and on during the week, but will  only do commits/PRs on the weekend for now.  Git stuff takes just as much time as developing.  But I'll get more efficient at it eventually.  😛

**Comment by Mashintime** [comment]
> @Mashintime here's a another needed feature request, I just got by instant message:
> 
> ```
> When pressing "CQ" or "PING", button should be disabled and bootstrap spinner should be inside the corresponding button. 
> https://getbootstrap.com/docs/5.2/components/spinners/
> ```
> 
> I suggest, creating a new function, we need to pass the html object to and a specific timeout, until it's getting released.
> 
> Challenge accepted? 😃

Yes.  I'll see what I can do.  HTML object of the beacon button I assume, correct?

**Comment by DJ2LS** [comment]
> > @Mashintime here's a another needed feature request, I just got by instant message:
> 
> > 
> 
> > ```
> 
> > When pressing "CQ" or "PING", button should be disabled and bootstrap spinner should be inside the corresponding button. 
> 
> > https://getbootstrap.com/docs/5.2/components/spinners/
> 
> > ```
> 
> > 
> 
> > I suggest, creating a new function, we need to pass the html object to and a specific timeout, until it's getting released.
> 
> > 
> 
> > Challenge accepted? 😃
> 
> 
> 
> Yes.  I'll see what I can do.  HTML object of the beacon button I assume, correct?

Yes. CQ, Ping.

But no hurry!

Also a needed feature: switching between byte/min and bit/s

**Comment by DJ2LS** [comment]
> I added a return in the spectrum/waterfall code for code that would never be needed in it's current use case.  If you never plan on showing the spectrum that would render above the waterfall if enabled I'd be happy to remove it.  But wanted to double check.
> 
> 
> 
> I'll work on things off and on during the week, but will  only do commits/PRs on the weekend for now.  Git stuff takes just as much time as developing.  But I'll get more efficient at it eventually.  😛 

I think we should leave it maybe we need it some time. 

Yes git needs time for learning but is great as soon as it's working. Also IDEs are a great help.

**Comment by Mashintime** [comment]
Gonna scratch this and start a new PR, paranoid I messed something up rebasing.

**Pull request closed without merging**
