### PR TITLE
show connected station in chat

### LINKED ISSUE #431: show "connect to" in chat
show "connect to" in chat for easier status check of the tnc. Adding this to top nav bar in chat might be a good position.

### PR DESCRIPTION
**Pull request by DJ2LS**
show connected station in chat closes #431

### CODE REVIEW

**Comment by DJ2LS** [comment]
@Mashintime @LA3QMA could you have a look if this is working more or less correctly? I was busy so I have no idea if this is still working. Feel free improving this if you want

**Comment by LA3QMA** [comment]
Seems to work as expected.

I initiated a chat from STATION1 to HOMEBASE.
The GUI for HOMEBASE says "Connected with: STATION1"

Tried to connect STATION2 to HOMEBASE at the same time and it seems to work ok.

When HOMEBASE receive a message the "Connected with" switch to the last received callsign.
When HOMEBASE sends a return message the "Connected with" switch to the correct callsign.

Should probably be a timeout after a while and remove the "Connected with"

**Comment by DJ2LS** [comment]
Good point with the timeout. @Mashintime do you have the time, implementing a timeout?

The timeout can be a separate PR I think. @LA3QMA could you Sonne the favour and creating a feature request / optimisation for this ?

**Comment by Mashintime** [comment]
Should be easy enough, I can continue the work here if that's ok.

**Comment by DJ2LS** [comment]
@Mashintime yes, this is okay I think.

**Comment by Mashintime** [comment]
@DJ2LS I believe this is ready for main, after your review.

**Pull request merged**
