### PR TITLE
GUI adjustments and help cards

### PR DESCRIPTION
**Pull request by DJ2LS**
This PR improves overall look of the GUI

### CODE REVIEW

**Comment by DJ2LS** [comment]
@Mashintime there are now help modals - Just have a look for the question marks. They need to be adjusted. As a native speaker this might be easier for you, I think.

**Comment by Mashintime** [comment]
Sure, I'd be happy to take a look.

**Comment by DJ2LS** [comment]
I already created examples for "my station" and "audio devices". Intention is, flatten learning curve for new users and making the application easier to use.

**Comment by DJ2LS** [comment]
@Mashintime , we're ready to merge I think.

**Comment by Mashintime** [comment]
I'm good with merging.

**Pull request merged**
