### PR TITLE
update info fields

### PR DESCRIPTION
**Pull request by DJ2LS**
### essential steps before merging this PR:

- [x] Update TNC
    - [x] CQ
    - [x] QRV
    - [x] PING
    - [x] BEACON
    - [x] ARQ SESSION
    - [x] ARQ DATA TRANSFER
- [x] Update GUI
    - [x] CQ
    - [x] QRV
    - [x] PING
    - [x] BEACON
    - [x] ARQ SESSION
    - [x] ARQ DATA TRANSFER
- [x] Update WIKI
- [x] After all: remove` static.INFO.append(`

<hr>

```
self.send_data_to_socket_queue(

)
```

arq= "transmission"
status="open, closed, opening, failed, transmitting, receiving, transmitted, received"
reason=" ... "

arq="session"
status="open, closed"

ping="transmitting, received"
cq="transmitting, received"
beacon="transmitting, received"
qrv="transmitting, received"

### CODE REVIEW

**Comment by DJ2LS** [comment]
self.send_data_to_socket_queue(

        )


arq= "transmission"
status="open, closed, opening, failed, transmitted, received"
reason=" ... "

arq="session"
status="open, closed"


ping="transmitting, received"
cq="transmitting, received"
beacon="transmitting, received"
qrv="transmitting, received"

**Comment by kronenpj** [comment]
I like where you're taking this. I've started adapting the tests to use the information from `SOCKET_QUEUE` instead of `static.INFO`.

**Comment by DJ2LS** [comment]
I reduced the amount of information which will be sent to socket. We can increase this later step by step, if we want to display more information. As a start let's get a running version, first.

**Comment by kronenpj** [comment]
In the process of refactoring the tests I notices a few inconsistencies in the new messages. For example: for CQ, the states are `transmitting` and `receiving` but for BEACON they are `transmitting` and `received` and for PING they are `sending` and `receiving`. 
Having a set list or enumeration of states, messages and other groups of similar things could help with this consistency.

**Comment by DJ2LS** [comment]
Yes I agree with you. But on the other side states are different for modes. So I'm not sure if this could cause some confusion. 
Maybe we could avoid problems with a good documentation 🤔

**Pull request merged**
