### PR TITLE
Install for Fedora 40

### PR DESCRIPTION
**Pull request by OH1KH**
This install script addition seems to run with Fedora 40

### CODE REVIEW

**Comment by DJ2LS** [comment]
@deejdeej could you do me the favour and reviewing it? You're most experienced with the scripts

**Comment by deejdeej** [comment]
> @deejdeej could you do me the favour and reviewing it? You're most experienced with the scripts

Yes, when I have the time I will review it and test it out.

**Comment by jstrahle** [comment]
Just tested the installation with the modified script, and it looks like python-devel should be added to the list of packages being installed.

**Comment by OH1KH** [comment]
Possible.
I did not test script in plain Fedora40 (that needs setting up new virtual machine).
Just seek corresponding Fedora packages for Debian/Ubuntu names.

As I have done other programming with this F40 there might been already loaded packages and perhaps that's why script passed through without python-devel loading.

With Fedora it is also possible to install 
sudo dnf groupinstall "Development Tools" "Development Libraries"

That is some kind of equivalent of the Debian build-essential package, but there comes also lot of unneeded stuff.

**Comment by jstrahle** [comment]
I will test installation with "plain" Fedora 40, and give input later.

**Comment by deejdeej** [comment]
Added support for Fedora 40 into the install script.  Tested on fresh Fedora 40 Workstation install.  Thanks for the code bits and hints @OH1KH and @jstrahle !

**Pull request closed without merging**
