### PR TITLE
PEP8 improvements 

### PR DESCRIPTION
**Pull request by DJ2LS**
...we need to be carefully...

### CODE REVIEW

**Review by kronenpj — APPROVED** [review]
Looks good so far!

**Comment by kronenpj** [comment]
Manually tested after my commit, everything still works.

**Review by kronenpj — COMMENTED** [review]
If you're happy with the changes so far, I suggest we commit this soon. There's plenty of improvements and it's getting a little hard to review unless it's done commit-by-commit.

**Comment by kronenpj** [comment]
Tested manually and everything still works.

**Comment by DJ2LS** [comment]
Yes, I agree. And we can start a new PEP8 session, as we wish, again.

**Pull request merged**
